version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:905806897463:task-definition/alten:12"
        LoadBalancerInfo:
          ContainerName: "gatewat"
          ContainerPort: 4000