
server:
  servlet:
    context-path: /customervehicle
  port: 6000

 
spring: 
  application: 
    name: customer-vehicle-service
  datasource: 
    driver-class-name: org.h2.Driver
    password: ~
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    username: sa
  h2: 
    console: 
      enabled: true
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect