hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    customer-vehicle-service:
        path: /customervehicle/**
        serviceId: customer-vehicle-service
        stripPrefix: false
        sensitiveHeaders:

    vehicle-status-service:
        path: /vehiclestatus/**
        serviceId: vehicle-status-service
        stripPrefix: false
        sensitiveHeaders:


server:
  port: 4000
